version: '3.8'

networks:
  frontend-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${FRONTEND_SUBNET}
  backend-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${BACKEND_SUBNET}
  db-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${DB_SUBNET}

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-net
    ports:
      - "${POSTGRES_PORT}:5432"
    command: 
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=256MB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0-ubuntu-latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_TIMEOUT: ${ZBX_TIMEOUT}
    ports:
      - "${ZABBIX_SERVER_PORT}:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    networks:
      - backend-net
      - db-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:7.0-ubuntu-latest
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix-server
    environment:
      DB_SERVER_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_SERVER_HOST: ${ZABBIX_SERVER_HOST}
      PHP_TZ: ${PHP_TZ}
    ports:
      - "${ZABBIX_WEB_HTTP_PORT}:8080"
      - "${ZABBIX_WEB_HTTPS_PORT}:8443"
    networks:
      - frontend-net
      - backend-net
      - db-net

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix-server
    environment:
      GF_INSTALL_PLUGINS: ${GRAFANA_PLUGINS}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - frontend-net
      - backend-net

volumes:
  postgres-data:
  snmptraps:
  grafana-data: